 // approx 2 kHz bandwidth
    .fast_loop_param.foc_param.pi_d.kp=.8,
    .fast_loop_param.foc_param.pi_d.ki=.08,
    .fast_loop_param.foc_param.pi_d.kp2=.25,
    .fast_loop_param.foc_param.pi_d.ki2=.03,
    .fast_loop_param.foc_param.pi_d.value2 = 100,
    .fast_loop_param.foc_param.pi_d.ki_limit=35,
    .fast_loop_param.foc_param.pi_d.command_max=40,
    .fast_loop_param.foc_param.pi_q.kp=.8,
    .fast_loop_param.foc_param.pi_q.ki=.08,
    .fast_loop_param.foc_param.pi_d.kp2=.25,
    .fast_loop_param.foc_param.pi_d.ki2=.03,
    .fast_loop_param.foc_param.pi_d.value2 = 100,
    .fast_loop_param.foc_param.pi_q.ki_limit=35,
    .fast_loop_param.foc_param.pi_q.command_max=40,
    .fast_loop_param.foc_param.current_filter_frequency_hz=20000,
    .fast_loop_param.foc_param.num_poles = 10,