
PARAM_FILE = ../param/param_freebot_g474_motor_enc.c
PARAM_OVERRIDE = A1.h A2.h A3.h A4.h A5.h A6.h
PARAM_BUILD_DIR := ../build/param

export

include ../../motorlib/scripts/configure_gcc.mk
include ../../motorlib/scripts/make_param.mk
