vpath %.cpp $(dir $(lastword $(MAKEFILE_LIST)))

$(BUILD_DIR)/config_obot_g474_trace_6enc.o: $(BUILD_DIR)/ma782_encoder.o
$(BUILD_DIR)/config_obot_g474_trace_13enc.o: $(BUILD_DIR)/ma782_encoder.o
$(BUILD_DIR)/config_obot_g474_motor_enc.o: $(BUILD_DIR)/ma7xx_encoder.o
$(BUILD_DIR)/config_obot_g474_tmotor_driver.o: $(BUILD_DIR)/ma7xx_encoder.o
$(BUILD_DIR)/config_obot_g474_osa14.o: $(BUILD_DIR)/ma782_encoder.o